'''
Fills the BP with data for testing.
'''
import os

def main():
    os.mkdir("BP/generated")
    for i in range(1, 6):
        with open(
                f'BP/generated/filter_generated_data_{i}.txt',
                'w',
                encoding='utf8'
        ) as f:
            f.write(
                f'This is file number {i} generated by fill_with_data.py\n')

if __name__ == "__main__":
    main()