# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto

builds:
  - id: binary
    goos:
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease
  - id: msi
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease
    hooks:
      post: go-msi make --msi dist/regolith-{{.Version}}.msi --version {{.Version}} --src .\templates --out .\go-msi-tmp

archives:
  - builds:
      - binary
    replacements:
      windows: Windows
      386: x86
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Tag }}"

changelog:
  filters:
    exclude:
      # For excluding docs related commits
      - '^docs:'
      # For excluding configuration related commits
      - '^config:'
      # For excluding small typo commits
      - '^typo:'
      # For excluding dependencies related commits
      - '^dep:'
  sort: asc

release:
  extra_files:
    - glob: "./**/regolith-*.msi"

#brews:
#  - tap:
#      owner: Bedrock-OSS
#      name: homebrew-regolith
#
#    # Your app's homepage.
#    # Default is empty.
#    homepage: ""
#
#    # Your app's description.
#    # Default is empty.
#    description: ""
